### ISSUE TITLE
Fallback to native Comctl32 functions not working in "taskdlgi" test

### ISSUE THREAD

**Issue by Snejp** [katahiromz/vista2xp#22]
After you convert test "taskdlgi" with vista2xpa and run it in newer Windows, it works fine. But it always calls emulated functions in "v2xctl32.dll" even when using DO_FALLBACK option.

I found out that GetModuleHandleA function returns NULL every time when its run in here:
https://github.com/katahiromz/vista2xp/blob/f6f18a18ce469471d57600283b1b693d4e980e8f/dlls/v2xctl32/v2xctl32.c#L828-L830
so native function pointers 's_pTaskDialog' and 's_pTaskDialogIndirect' are also NULL and they cannot be run:
https://github.com/katahiromz/vista2xp/blob/f6f18a18ce469471d57600283b1b693d4e980e8f/dlls/v2xctl32/v2xctl32.c#L776-L780

Test "taskdlg" is running as intended because it uses InitCommonControls() (it could be any function from comctl32) which force to load a "comctl32.dll" to a process memory.

**Comment by katahiromz** [comment]
Please create a Pull Request.

**Comment by katahiromz** [comment]
Fixed.
