### ISSUE TITLE
Some backported functions from microsoft?

### ISSUE THREAD

**Issue by tumagonx** [katahiromz/vista2xp#23]
I'm rooting for this project to move forward!

there are several .obj/.lib of interest that provide "official" backported functions
msvcrt_winxp.obj (part of WDK/DDK) : provide some secure api
fileextd.lib (independent / part of WSDK) : with the help of fileextd.h ([download](http://web.archive.org/web/20061124104838/http://download.microsoft.com/download/0/f/e/0fe2a777-5ac5-40d1-8700-86169b182eda/Win32%20FileID%20APIs%201.1.EXE)) this provide OpenFileById, GetFileInformationByHandleEx, SetFileInformationByHandle. note that the one shipped with WSDK need Windows NT 5.2 (2003/XP64).

Do you plan to include them?

non-microsoft:
Use pthread based emulation for ThreadingAPI?

**Comment by katahiromz** [comment]
Busy.

**Comment by katahiromz** [comment]
Link dead.

**Comment by katahiromz** [comment]
Analyzing...

**Comment by katahiromz** [comment]
Analyzed.
https://github.com/katahiromz/WonFileID

**Comment by katahiromz** [comment]
Done.
