### ISSUE TITLE
xp to vista?

### ISSUE THREAD

**Issue by RandomPSPguy** [katahiromz/vista2xp#24]
How would someone go about making xp's shell usable on server 2008 core? 

Using windows XP's source code to compile, would all I have to do is use a .def file and forward the newer functions to another dll for example vistashell32.dll and keep the original code the same? 

What do I do about ordinals? do I need to find their real names or can I just forward the ordinal by itself?

I really want to be able to run XP's explorer.exe on a newer kernel. So any help or explanation on how to do that with XP's source would be appreciated.

**Comment by katahiromz** [comment]
This application is not for the system files. Sorry.
