### ISSUE TITLE
Windows XP SP3 PosReady2009 - ADVAPI32.RegDeleteKeyExW

### ISSUE THREAD

**Issue by LordGarfio** [katahiromz/vista2xp#27]
Hi katahiromz,

Vista2XP is really a very COOL program. 

I have tried your nice vista2xp application on ImgDrive v2.1.8 Freeware from www.yubsoft.com/imgdrive, without success.

The RegDeleteKeyExW function of ADVAPI32.dll is not recognized.

Could you support it if it is not a hassle?.

Thank you in advanced.

**Comment by katahiromz** [comment]
Can you test this?

https://github.com/katahiromz/vista2xp/releases/tag/0.8.2

Thanks.

**Comment by katahiromz** [comment]
Sorry, it doesn't work. I will retry.

**Comment by katahiromz** [comment]
Fixed.

**Comment by LordGarfio** [comment]
Hello, I have tried your tools without success in general.
· vista2xp v0.8.4 by katahiromz.
· vista2xp v0.8.3 by katahiromz.
· vista2xp v0.8.2 by katahiromz.

RegDeleteKeyExW ERROR:
ImgDrive v2.1.8 FREEWARE PORTABLE by www.yubsoft.com/imgdrive do not works still.
RegDeleteKeyExW ERROR:
![ImgDrive v2 1 8 XP](https://github.com/katahiromz/vista2xp/assets/65074751/42f84af3-aced-4430-a67c-6c5b3c1593f8)

Direct Folders v4.2 Freeware Installer and TeraCopy Pro v3.17 Freeware Installer by Code Sector which is using Advanced Installer v21.1.x from www.caphyon.com.
CreateEventExW ERROR:
![Direct Folders v4 2 Free Installer](https://github.com/katahiromz/vista2xp/assets/65074751/702b5901-ac44-4f13-bf62-7dce04d588fd)
![TeraCopy Pro v3 17 Free Installer](https://github.com/katahiromz/vista2xp/assets/65074751/198924a0-8640-4d97-a9d0-798a55f65c5b)

FastCopy v5.7.12 ERROR:
![FastCopy x32 v5 7 12 XP](https://github.com/katahiromz/vista2xp/assets/65074751/62f4aea9-66b7-492b-b7de-605570a25e60)

FastCopy v5.7.12 FREEWARE by fastcopy.jp With Vista-to-XP application converter, WORKS very good.
![FastCopy x32 v5 7 12 XP works](https://github.com/katahiromz/vista2xp/assets/65074751/08426fbf-eeda-4402-8d3a-2df4f67329ac)

Thank you in advanced.

**Comment by LordGarfio** [comment]
Hello, I have tried your tools without success in general.
· vista2xp v0.8.4 by katahiromz.
· vista2xp v0.8.3 by katahiromz.
· vista2xp v0.8.2 by katahiromz.
